<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(TargetFramework)</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentAssertions" Version="$(FluentAssertions)" />
    <PackageReference Include="Moq" Version="$(Moq)" />
    <PackageReference Include="nunit" Version="$(nunit)" />
    <PackageReference Include="NUnit3TestAdapter" Version="$(NUnit3TestAdapter)" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="$(MicrosoftNETTestSdk)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Payments.Infrastructure\Payments.Infrastructure.csproj" />
    <ProjectReference Include="..\Payments.CommandHandlers\Payments.CommandHandlers.csproj" />
  </ItemGroup>

</Project>
