<Project>
    <PropertyGroup Label="Сommon properties">
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>latest</LangVersion>
    </PropertyGroup>

    <PropertyGroup Label="Packages dependency microsoft">
        <EntityFrameworkCore>10.0.12</EntityFrameworkCore>
        <EntityFrameworkCorePostgreSQL>10.0.3</EntityFrameworkCorePostgreSQL>
        <EFCoreNamingConventions>1.1.1</EFCoreNamingConventions>
        <AspNetCoreMvcTesting>10.0.12</AspNetCoreMvcTesting>
        <AspNetCoreOpenApi>10.0.12</AspNetCoreOpenApi>
        <HealthChecksEntityFrameworkCore>10.0.12</HealthChecksEntityFrameworkCore>

        <MicrosoftNETTestSdk>18.10.1</MicrosoftNETTestSdk>
        <Dapper>2.1.89</Dapper>
        <MicrosoftDataSqliteCore>10.0.12</MicrosoftDataSqliteCore>

        <MicrosoftAspNetCoreMvcNewtonsoftJson>3.1.18</MicrosoftAspNetCoreMvcNewtonsoftJson>
        <MicrosoftAspNetCoreMvc>2.2.0</MicrosoftAspNetCoreMvc>
        <NewtonsoftJson>13.0.4</NewtonsoftJson>
        <ConfigurationJson>10.0.12</ConfigurationJson>
        <Swashbuckle>10.3.0</Swashbuckle>
        <FluentValidation>8.6.3</FluentValidation>
        <coverletcollector>3.0.2</coverletcollector>

        <MediatR>13.1.0</MediatR>
        <Scrutor>3.3.0</Scrutor>
        <DotNetTestcontainers>1.6.0</DotNetTestcontainers>
        <SeleniumSupport>3.141.0</SeleniumSupport>
        <WebDriverChromeDriver>95.0.4638.5401</WebDriverChromeDriver>

        <SpecFlowPlusLivingDocPlugin>3.9.57</SpecFlowPlusLivingDocPlugin>
        <SpecFlowNUnit>3.9.74</SpecFlowNUnit>
        <Bogus>35.6.5</Bogus>
        <nunit>3.14.0</nunit>
        <NUnit3TestAdapter>5.2.0</NUnit3TestAdapter>
        <FluentAssertions>6.12.2</FluentAssertions>

        <coverletmsbuild>6.0.4</coverletmsbuild>
        <Moq>4.20.72</Moq>
        <NBuilder>6.1.0</NBuilder>
        <ReportGenerator>5.5.11</ReportGenerator>
    </PropertyGroup>

</Project>