# This docker-compose runs infrastructure required to host the services.

version: '3'

services:
  postgres:
      image: postgres
      container_name: e-commerce-order
      ports:
          - 5432:5432
      environment:
          POSTGRES_PASSWORD: "jTHSuuwu7#@"
          POSTGRES_USER: e-commerce
          POSTGRES_DB: ecommerce-order
      volumes:
          - /postgresql/data 
      networks:
          - ecommerce-networks
  
networks: 
    ecommerce-networks:
        driver: bridge