version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: postgres_main
    restart: always
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
      POSTGRES_MULTIPLE_DATABASES: customers,catalog,payment,orders
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ecommerce-networks

volumes:
  postgres_data:
    
networks: 
    ecommerce-networks:
        driver: bridge