@Catalog.Web.Api_HostAddress = http://localhost:5064

# pageNumber (padrão 1) e pageSize (padrão e máximo 20) são opcionais.
GET {{Catalog.Web.Api_HostAddress}}/GetAllProducts?pageNumber=1&pageSize=10
Accept: application/json

###

GET {{Catalog.Web.Api_HostAddress}}/GetProductById/1
Accept: application/json

###
