<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>$(TargetFramework)</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="MediatR" Version="$(MediatR)" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Payments.Domain\Payments.Domain.csproj" />
    </ItemGroup>

</Project>
