<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(TargetFramework)</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentAssertions" Version="$(FluentAssertions)" />
    <PackageReference Include="Moq" Version="$(Moq)" />
    <PackageReference Include="nunit" Version="$(nunit)" />
    <PackageReference Include="NUnit3TestAdapter" Version="$(NUnit3TestAdapter)" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="$(MicrosoftNETTestSdk)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Gateway.Payment.Data\Gateway.Payment.Data.csproj" />
    <ProjectReference Include="..\Gateway.Payment.CommandHandlers\Gateway.Payment.CommandHandlers.csproj" />
  </ItemGroup>

</Project>
