// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Store.Infrastructure;

namespace Store.Infrastructure.Migrations
{
    [DbContext(typeof(OrderContext))]
    [Migration("20190828140849_v1")]
    partial class v1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Store.Domain.Models.Orders.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("CustomerId")
                        .HasColumnName("CustomerId");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnName("OrderDate");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnName("OrderNumber");

                    b.Property<Guid>("PaymentId")
                        .HasColumnName("PaymentId");

                    b.HasKey("Id")
                        .HasName("OrderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Store.Domain.Models.Orders.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Discount");

                    b.Property<int>("OrderId");

                    b.Property<string>("PictureUrl");

                    b.Property<Guid>("ProductId");

                    b.Property<string>("ProductName")
                        .IsRequired();

                    b.Property<decimal>("UnitPrice");

                    b.Property<int>("Units");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Store.Domain.Models.Orders.Order", b =>
                {
                    b.OwnsOne("Store.Domain.Models.Orders.OrderAddress", "Address", b1 =>
                        {
                            b1.Property<int>("OrderId")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("City")
                                .HasColumnName("AddressCity");

                            b1.Property<string>("Country")
                                .HasColumnName("AddressCountry");

                            b1.Property<string>("State")
                                .HasColumnName("AddressState");

                            b1.Property<string>("Street")
                                .HasColumnName("AddressStreet");

                            b1.Property<string>("ZipCode")
                                .HasColumnName("AddressZipCode");

                            b1.HasKey("OrderId");

                            b1.ToTable("Orders");

                            b1.HasOne("Store.Domain.Models.Orders.Order")
                                .WithOne("Address")
                                .HasForeignKey("Store.Domain.Models.Orders.OrderAddress", "OrderId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("Store.Domain.Models.Orders.OrderStatus", "Status", b1 =>
                        {
                            b1.Property<int>("OrderId")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<int>("Code")
                                .HasColumnName("StatusCode");

                            b1.Property<string>("Name")
                                .HasColumnName("StatusName");

                            b1.HasKey("OrderId");

                            b1.ToTable("Orders");

                            b1.HasOne("Store.Domain.Models.Orders.Order")
                                .WithOne("Status")
                                .HasForeignKey("Store.Domain.Models.Orders.OrderStatus", "OrderId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("Store.Domain.Models.Orders.OrderItem", b =>
                {
                    b.HasOne("Store.Domain.Models.Orders.Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
